version: 0.2

phases:

  build:
    on-failure: ABORT
    commands:
    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${ECR_REGISTRY}

    - |
      publish() {
        dir=$1
      
        cd $1
        docker pull ${ECR_REGISTRY}/docker-hub/webpronl/reveal-md
        docker-compose up
        aws s3 rm --recursive s3://${S3CFBUCKET}/present/$1 || echo 'delete skipped'
        aws s3 cp --recursive $1 s3://${S3CFBUCKET}/present/$1
        aws s3 cp --recursive images s3://${S3CFBUCKET}/present/$1/images

        aws cloudfront create-invalidation --distribution-id ${CFDISTRIBUTIONID} --paths /present/$1/* --region us-east-1

        cd ..
      }
      
      # the following presentations are now static
      # publish opensearch
      # publish monthly_ops

      # actively maintained presentations
      publish zk